export enum AccessModeSubModuleEnum {
  NotSelected = 'not-selected',
  management = 'management',
  Disciplines = 'disciplines',
  Structure = 'structure',
  Regulations = 'regulations',
  Strategies = 'strategies',
  CorporateStyle = 'corporate-style',
  Legislation = 'legislation',
  Careers = 'careers',
  Grants = 'grants',
  Reports = 'reports',
  Departments = 'departments',
  Sectors = 'sectors',
  ActionPlan = 'action-plan',
  YouthHouses = 'youth-houses',
  NgoYouthOrganizations = 'ngo-youth-organizations',
  SportsEquipment = 'sports-equipment',
  AthletesRatings = 'athletes-ratings',
  HealthyLife = 'healthy-life',
  ContactDetails = 'contact-details',
  CivicReception = 'civic-reception',
  IdeologicalBank = 'ideological-bank',
  Categories = 'categories',
}
